# -*- coding: utf-8 -*-
import json, re, unicodedata

def slugify_id(name, disc):
    s = re.sub(r'[^a-zA-Z0-9]+', '-', name.lower()).strip('-')
    return f"d{disc}-{s}"

GENRE_DEFAULTS = {
    "Lucha": {"dificultad": 3, "jugadores": "1-2", "cat": "Lucha"},
    "Lucha / Acción": {"dificultad": 3, "jugadores": "1-2", "cat": "Lucha"},
    "Lucha / Urbano": {"dificultad": 3, "jugadores": "1-2", "cat": "Lucha"},
    "Lucha / Anime": {"dificultad": 3, "jugadores": "1-2", "cat": "Lucha"},
    "Lucha / Arcade": {"dificultad": 3, "jugadores": "1-2", "cat": "Lucha"},
    "Lucha Libre": {"dificultad": 2, "jugadores": "1-4", "cat": "Lucha"},
    "Deportes / Boxeo": {"dificultad": 3, "jugadores": "1-2", "cat": "Deportes"},
    "Deportes": {"dificultad": 2, "jugadores": "1-4", "cat": "Deportes"},
    "Arcade / Accion": {"dificultad": 3, "jugadores": "1-2", "cat": "Arcade"},
    "Arcade / Colección": {"dificultad": 2, "jugadores": "1-2", "cat": "Arcade"},
    "Mundo Abierto": {"dificultad": 4, "jugadores": "1", "cat": "Mundo Abierto"},
    "Mundo Abierto / Acción": {"dificultad": 4, "jugadores": "1", "cat": "Mundo Abierto"},
    "Acción / Mundo Abierto": {"dificultad": 4, "jugadores": "1", "cat": "Mundo Abierto"},
    "Acción / Infiltración": {"dificultad": 4, "jugadores": "1", "cat": "Sigilo"},
    "Sigilo / Acción": {"dificultad": 4, "jugadores": "1", "cat": "Sigilo"},
    "Sigilo / Espionaje": {"dificultad": 4, "jugadores": "1", "cat": "Sigilo"},
    "Acción / Hack and Slash": {"dificultad": 4, "jugadores": "1", "cat": "Hack and Slash"},
    "Hack and Slash": {"dificultad": 4, "jugadores": "1", "cat": "Hack and Slash"},
    "Shooter / Belérico": {"dificultad": 4, "jugadores": "1-2", "cat": "Shooter"},
    "Shooter en Primera Persona": {"dificultad": 4, "jugadores": "1-2", "cat": "Shooter"},
    "Shooter Táctico": {"dificultad": 5, "jugadores": "1", "cat": "Shooter"},
    "Shooter / Noir": {"dificultad": 4, "jugadores": "1", "cat": "Shooter"},
    "Shooter / Acción": {"dificultad": 4, "jugadores": "1-2", "cat": "Shooter"},
    "Acción / Mecha": {"dificultad": 4, "jugadores": "1", "cat": "Acción"},
    "Survival Horror": {"dificultad": 4, "jugadores": "1", "cat": "Survival Horror"},
    "Aventura Épica": {"dificultad": 4, "jugadores": "1", "cat": "Aventura"},
    "Aventura / Puzzle": {"dificultad": 3, "jugadores": "1", "cat": "Aventura"},
    "Aventura / Acción": {"dificultad": 3, "jugadores": "1", "cat": "Aventura"},
    "Acción / Aventura": {"dificultad": 3, "jugadores": "1", "cat": "Aventura"},
    "Aventura / Plataformas": {"dificultad": 2, "jugadores": "1", "cat": "Plataformas"},
    "Carreras / Tuning": {"dificultad": 3, "jugadores": "1-2", "cat": "Carreras"},
    "Carreras / Arcade": {"dificultad": 2, "jugadores": "1-2", "cat": "Carreras"},
    "Carreras / Mundo Abierto": {"dificultad": 3, "jugadores": "1-2", "cat": "Carreras"},
    "Carreras": {"dificultad": 2, "jugadores": "1-2", "cat": "Carreras"},
    "Simulador de Conducción": {"dificultad": 3, "jugadores": "1-2", "cat": "Carreras"},
    "Acción / Beat 'em up": {"dificultad": 3, "jugadores": "1-2", "cat": "Beat 'em up"},
    "Beat 'em up": {"dificultad": 3, "jugadores": "1-2", "cat": "Beat 'em up"},
    "Acción / RPG": {"dificultad": 3, "jugadores": "1", "cat": "RPG"},
    "RPG / Aventura": {"dificultad": 3, "jugadores": "1", "cat": "RPG"},
    "Musical / Trivia": {"dificultad": 2, "jugadores": "1-4", "cat": "Fiesta"},
}
DEFAULT_GENRE = {"dificultad": 3, "jugadores": "1", "cat": "Acción"}

SYNOPSIS_TPL = {
    "Lucha": "Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.",
    "Deportes": "Simulador deportivo para PS2 con modos de temporada, torneos y partidas rápidas.",
    "Arcade": "Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.",
    "Mundo Abierto": "Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.",
    "Sigilo": "Juego de sigilo y estrategia táctica. Evitá ser detectado y planificá cada movimiento.",
    "Hack and Slash": "Acción frenética con combos cuerpo a cuerpo contra oleadas de enemigos.",
    "Shooter": "Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.",
    "Survival Horror": "Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.",
    "Aventura": "Aventura de acción con exploración, resolución de puzzles y una historia envolvente.",
    "Plataformas": "Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.",
    "Carreras": "Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.",
    "Beat 'em up": "Beat 'em up clásico: avanzá por el escenario repartiendo golpes contra hordas de enemigos.",
    "RPG": "RPG de acción con progresión de personaje, historia profunda y combates estratégicos.",
    "Fiesta": "Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.",
    "Acción": "Título de acción para PS2 con ritmo intenso y desafíos variados.",
}

def build(name, genre_raw, disc, extra_id=""):
    g = GENRE_DEFAULTS.get(genre_raw, DEFAULT_GENRE)
    cat = g["cat"]
    return {
        "id": slugify_id(name, disc) + extra_id,
        "nombre": name,
        "disco": disc,
        "categoria": cat,
        "genero_original": genre_raw,
        "dificultad": g["dificultad"],
        "jugadores": g["jugadores"],
        "resena": SYNOPSIS_TPL.get(cat, SYNOPSIS_TPL["Acción"]),
    }

disco1 = [
("Dragon Ball Z: Budokai Tenkaichi 3","Lucha / Acción"),
("Mortal Kombat: Armageddon","Lucha"),
("Mortal Kombat: Deception","Lucha"),
("Tekken 5","Lucha"),
("The King of Fighters XI","Lucha"),
("The King of Fighters 2002 UM","Lucha"),
("Street Fighter Alpha Anthology","Lucha"),
("Capcom vs. SNK 2","Lucha"),
("Guilty Gear XX Accent Core","Lucha"),
("Soulcalibur III","Lucha"),
("Def Jam: Fight for NY","Lucha / Urbano"),
("Naruto: Ultimate Ninja 3","Lucha / Anime"),
("Bloody Roar 4","Lucha"),
("Virtua Fighter 4 Evolution","Lucha"),
("Marvel vs. Capcom 2","Lucha"),
("WWE SmackDown! Here Comes the Pain","Lucha Libre"),
("WWE SmackDown! vs. RAW","Lucha Libre"),
("Fight Night Round 3","Deportes / Boxeo"),
("Def Jam Vendetta","Lucha / Urbano"),
("Samurai Shodown Anthology","Lucha / Arcade"),
("Metal Slug Anthology","Arcade / Accion"),
("Bloody Roar 3","Lucha"),
("Super Dragon Ball Z","Lucha"),
("Garou: Mark of the Wolves","Lucha"),
("SVC Chaos: SNK vs. Capcom","Lucha"),
]

disco3 = [
("Grand Theft Auto: San Andreas","Mundo Abierto"),
("Grand Theft Auto: Vice City","Mundo Abierto"),
("Grand Theft Auto III","Mundo Abierto"),
("Metal Gear Solid 3: Snake Eater","Acción / Infiltración"),
("Metal Gear Solid 2: Sons of Liberty","Acción / Infiltración"),
("God of War","Acción / Hack and Slash"),
("God of War II","Acción / Hack and Slash"),
("Call of Duty: Finest Hour","Shooter / Belérico"),
("Call of Duty 2: Big Red One","Shooter / Belérico"),
("Call of Duty 3","Shooter / Belérico"),
("Armored Core: Last Raven","Acción / Mecha"),
("Armored Core 3","Acción / Mecha"),
("Armored Core: Nexus","Acción / Mecha"),
("Armored Core: Nine Breaker","Acción / Mecha"),
("Resident Evil 4","Survival Horror"),
("Resident Evil - Code: Veronica X","Survival Horror"),
("Resident Evil Outbreak","Survival Horror"),
("Resident Evil Outbreak: File #2","Survival Horror"),
("Silent Hill 2","Survival Horror"),
("Silent Hill 3","Survival Horror"),
("Silent Hill 4: The Room","Survival Horror"),
("Silent Hill: Origins","Survival Horror"),
("Medal of Honor: Frontline","Shooter en Primera Persona"),
("Medal of Honor: Rising Sun","Shooter / Belérico"),
("Medal of Honor: European Assault","Shooter / Belérico"),
("Shadow of the Colossus","Aventura Épica"),
("Ico","Aventura / Puzzle"),
("Okami","Aventura / Acción"),
("Devil May Cry","Hack and Slash"),
("Devil May Cry 3: Dante's Awakening","Hack and Slash"),
("Prince of Persia: The Sands of Time","Aventura / Plataformas"),
("Prince of Persia: Warrior Within","Aventura / Acción"),
("Prince of Persia: The Two Thrones","Aventura / Acción"),
("Bully","Mundo Abierto / Acción"),
("Max Payne","Shooter / Noir"),
("Max Payne 2: The Fall of Max Payne","Shooter / Noir"),
("Need for Speed: Most Wanted","Carreras / Tuning"),
("Need for Speed: Underground 2","Carreras / Tuning"),
("Burnout 3: Takedown","Carreras / Arcade"),
("Midnight Club 3: DUB Edition","Carreras / Mundo Abierto"),
("Gran Turismo 4","Simulador de Conducción"),
("Gran Turismo 3: A-Spec","Simulador de Conducción"),
("Killzone","Shooter en Primera Persona"),
("Timesplitters 2","Shooter / Acción"),
("Timesplitters: Future Perfect","Shooter / Acción"),
("The Matrix: Path of Neo","Acción / Beat 'em up"),
("Enter the Matrix","Acción / Aventura"),
("Onimusha: Warlords","Acción / Aventura"),
("Onimusha 2: Samurai's Destiny","Acción / Aventura"),
("Onimusha 3: Demon Siege","Acción / Aventura"),
("Onimusha: Dawn of Dreams","Acción / Aventura"),
("Castlevania: Curse of Darkness","Acción / RPG"),
("Castlevania: Lament of Innocence","Acción / RPG"),
("God Hand","Beat 'em up"),
("Mercenaries: Playground of Destruction","Acción / Mundo Abierto"),
("True Crime: Streets of LA","Mundo Abierto"),
("True Crime: New York City","Mundo Abierto"),
("Scarface: The World is Yours","Mundo Abierto"),
("The Godfather","Mundo Abierto"),
("Hitman: Blood Money","Sigilo / Acción"),
("Hitman 2: Silent Assassin","Sigilo / Acción"),
("Splinter Cell: Chaos Theory","Sigilo / Espionaje"),
("Tom Clancy's Ghost Recon","Shooter Táctico"),
]

coleccion = [
("Activision Anthology","Arcade / Colección"),
("Alien Hominid","Acción / Aventura"),
("Naruto: Clash of Ninja Revolution 3","Acción / Aventura"),
("Naruto: Ultimate Ninja","Acción / Aventura"),
("Naruto: Ultimate Ninja Zero 3","Acción / Aventura"),
("Art of Fighting Anthology","Lucha / Acción"),
("Atari Anthology","Arcade / Colección"),
("Baldur's Gate: Dark Alliance","RPG / Aventura"),
("Baldur's Gate: Dark Alliance 2","RPG / Aventura"),
("Baroque","RPG / Aventura"),
("Battlefield 2: Modern Combat","Shooter / Acción"),
("Blood Will Tell","Acción / Aventura"),
("Bloody Roar 3","Lucha / Acción"),
("Burnout 3: Takedown","Carreras"),
("Burnout Dominator","Carreras"),
("Buzz! Hollywood","Musical / Trivia"),
("Buzz! Junior: Dino Den","Musical / Trivia"),
("Buzz! Junior: Monster Rumble","Musical / Trivia"),
("Buzz! The Big Quiz","Musical / Trivia"),
("Buzz! The Pop Quiz","Musical / Trivia"),
("Buzz! The Sports Quiz","Musical / Trivia"),
("Buzz! ¿Qué Sabes de tu País?","Musical / Trivia"),
("Capcom Classics Collection Vol.1","Arcade / Colección"),
("Capcom Classics Collection Vol.2","Arcade / Colección"),
("Castlevania: Curse of Darkness","Acción / Aventura"),
("Contra: Shattered Soldier","Shooter / Acción"),
("Crash Bandicoot: Nitro Kart","Carreras"),
("Crash Twinsanity","Aventura / Plataformas"),
("Darkwatch","Shooter / Acción"),
("Def Jam: Fight for NY","Lucha / Acción"),
("Devil May Cry 2 (Dante Disc)","Acción / Aventura"),
("Devil May Cry 2 (Lucia Disc)","Acción / Aventura"),
("Downhill Domination","Carreras"),
("Dragon Blaze","Acción / Aventura"),
("Echo Night: Beyond","Survival Horror"),
("Fatal Fury Battle Archives Vol.2","Lucha / Acción"),
("FIFA Street","Deportes"),
("Final Fantasy X","RPG / Aventura"),
("Final Fantasy X-2","RPG / Aventura"),
("Final Fantasy XII","RPG / Aventura"),
("Forgotten Realms: Demon Stone","RPG / Aventura"),
("Gitaroo Man","Aventura / Plataformas"),
("God of War","Acción / Aventura"),
("God of War II","Acción / Aventura"),
("Gradius III & IV","Acción / Aventura"),
("Guitar Hero III: Legends of Rock","Musical / Trivia"),
("Gunbird: Special Edition","Acción / Aventura"),
("The Guy Game","Acción / Aventura"),
("The Hobbit","Acción / Aventura"),
("Jacked","Acción / Aventura"),
("Jak and Daxter: The Lost Frontier","Aventura / Plataformas"),
("Just Cause","Acción / Aventura"),
("Kinetica","Carreras"),
("King of Fighters 2000 & 2001 (Disc 2)","Lucha / Acción"),
("Knights of the Temple II","Aventura / Plataformas"),
("Manhunt","Acción / Aventura"),
("MegaMan Anniversary Collection","Arcade / Colección"),
("MegaMan X Collection","Arcade / Colección"),
("Metal Gear Solid 2: Sons of Liberty","Shooter / Acción"),
("Metal Slug Anthology","Arcade / Colección"),
("Midway Arcade Treasures 2","Arcade / Colección"),
("Midway Arcade Treasures 3","Arcade / Colección"),
("Mortal Kombat: Armageddon","Lucha / Acción"),
("Mortal Kombat: Deception","Lucha / Acción"),
("Mushihimesama","Acción / Aventura"),
("MX vs. ATV Untamed","Carreras"),
("MX vs. ATV Unleashed","Carreras"),
("MX World Tour","Carreras"),
("Namco Museum","Arcade / Colección"),
("NBA Live 09","Deportes"),
("Need for Speed: Most Wanted","Carreras"),
("Neo Contra","Shooter / Acción"),
("NeoGeo Fatal Fury Collection","Lucha / Acción"),
("NiGHTS into Dreams...","Aventura / Plataformas"),
("Ninja Assault","Shooter / Acción"),
("Obscure","Survival Horror"),
("Obscure II","Survival Horror"),
("Odin Sphere","RPG / Aventura"),
("Onimusha: Warlords","Acción / Aventura"),
("Onimusha 2: Samurai's Destiny","Lucha / Acción"),
("Onimusha 3: Demon Siege","Acción / Aventura"),
("Outrun 2006: Coast 2 Coast","Carreras"),
("Pac-Man World Rally","Acción / Aventura"),
("Prince of Persia: The Sands of Time","Acción / Aventura"),
("Prince of Persia: The Two Thrones","Acción / Aventura"),
("Prince of Persia: Warrior Within","Acción / Aventura"),
("Primal","Acción / Aventura"),
("Pro Evolution Soccer 2014","Deportes"),
("Project Zero","Survival Horror"),
("Project Zero 2: Crimson Butterfly","Survival Horror"),
("Project Zero 3: The Tormented","Survival Horror"),
("The Punisher","Acción / Aventura"),
("Radirgy: Precious","Acción / Aventura"),
("Ratchet & Clank","Aventura / Plataformas"),
("Ratchet & Clank 2: Locked & Loaded","Aventura / Plataformas"),
("Ratchet & Clank 3: Up Your Arsenal","Aventura / Plataformas"),
("Ratchet: Deadlocked","Aventura / Plataformas"),
("Resident Evil: Code Veronica X","Survival Horror"),
("Resident Evil Outbreak","Survival Horror"),
("Resident Evil 4","Survival Horror"),
("Resident Evil Outbreak: File #2","Survival Horror"),
("Rule of Rose","Survival Horror"),
("Rumble Roses","Lucha / Acción"),
("Rygar: The Legendary Adventure","Acción / Aventura"),
("Saint Seiya: The Sanctuary","Acción / Aventura"),
("Samurai Shodown Anthology","Lucha / Acción"),
("Second Sight","Shooter / Acción"),
("Sega Classics Collection","Arcade / Colección"),
("Sega Genesis Collection","Arcade / Colección"),
("Shadow Hearts","RPG / Aventura"),
("Shadow of Rome","Acción / Aventura"),
("Shadow Tower Abyss","Survival Horror"),
("Shin Megami Tensei: Digital Devil Saga","RPG / Aventura"),
("Silent Hill: Origins","Survival Horror"),
("Silent Hill: Shattered Memories","Survival Horror"),
("Silent Hill 2","Survival Horror"),
("Silent Hill 3","Survival Horror"),
("Silent Hill 4: The Room","Survival Horror"),
("The Simpsons: Hit & Run","Aventura / Plataformas"),
("Sly 3: Honor Among Thieves","Aventura / Plataformas"),
("Sly Cooper and the Thievius Raccoonus","Aventura / Plataformas"),
("Sly 2: Band of Thieves","Aventura / Plataformas"),
("SNK Arcade Classics Volume 1","Arcade / Colección"),
("Sonic Gems Collection","Aventura / Plataformas"),
("Sonic Heroes","Aventura / Plataformas"),
("Sonic Riders: Zero Gravity","Carreras"),
("Sonic Unleashed","Aventura / Plataformas"),
("Soulcalibur III","Lucha / Acción"),
("Soulcalibur II","Lucha / Acción"),
("Spartan: Total Warrior","Acción / Aventura"),
("Splatterhouse","Acción / Aventura"),
("Spyro: A Hero's Tail","Aventura / Plataformas"),
("Spyro: Enter the Dragonfly","Aventura / Plataformas"),
("Street Fighter Alpha Anthology","Lucha / Acción"),
("Street Fighter Anniversary Collection","Lucha / Acción"),
("The Suffering","Survival Horror"),
("The Suffering: Ties That Bind","Survival Horror"),
("Super Mario 64 (ROM)","Aventura / Plataformas"),
("TMNT: Teenage Mutant Ninja Turtles","Acción / Aventura"),
("Taiko no Tatsujin 10 in 1","Musical / Trivia"),
("Taito Legends 2","Arcade / Colección"),
("Tales of the Abyss","RPG / Aventura"),
("Tekken 4","Lucha / Acción"),
("Tekken 5","Lucha / Acción"),
("Tekken Tag Tournament","Lucha / Acción"),
("The Fellowship of the Ring","Acción / Aventura"),
("The Hobbit","Acción / Aventura"),
("The King of Fighters 10 in 1","Lucha / Acción"),
("The Thing","Acción / Aventura"),
("Time Crisis 2","Shooter / Acción"),
("Time Crisis 3","Shooter / Acción"),
("TimeSplitters","Shooter / Acción"),
("TimeSplitters: Future Perfect","Shooter / Acción"),
("TimeSplitters 2","Shooter / Acción"),
("Urban Chaos: Riot Response","Acción / Aventura"),
("Valkyrie Profile 2: Silmeria","RPG / Aventura"),
("Vampire: Darkstalkers Collection","Arcade / Colección"),
("Vampire Night","Shooter / Acción"),
("Viewtiful Joe","Acción / Aventura"),
("Viewtiful Joe 2","Acción / Aventura"),
("Virtua Cop: Elite Edition","Lucha / Acción"),
("Warhammer 40,000: Fire Warrior","RPG / Aventura"),
("Wipeout Pulse","Carreras"),
("World Heroes Anthology","Arcade / Colección"),
("Worms Blast","Acción / Aventura"),
("XG3: Extreme-G Racing","Carreras"),
("Yakuza","Acción / Aventura"),
("Yakuza 2","Acción / Aventura"),
("Giga Wing Generations","Acción / Aventura"),
]

games = []
seen_ids = {}
for name, genre in disco1:
    g = build(name, genre, 1)
    while g["id"] in seen_ids:
        g["id"] += "-b"
    seen_ids[g["id"]] = True
    games.append(g)

for name, genre in disco3:
    g = build(name, genre, 3)
    while g["id"] in seen_ids:
        g["id"] += "-b"
    seen_ids[g["id"]] = True
    games.append(g)

for name, genre in coleccion:
    g = build(name, genre, "C")
    while g["id"] in seen_ids:
        g["id"] += "-b"
    seen_ids[g["id"]] = True
    games.append(g)

discos = [
    {"id": 1, "nombre": "Disco 1", "subtitulo": "Lucha y Acción Rápida", "color": "#e63946"},
    {"id": 3, "nombre": "Disco 3", "subtitulo": "Mundo Abierto, Aventura y Disparos", "color": "#1d3557"},
    {"id": "C", "nombre": "Colección", "subtitulo": "Listado Alfabético Adicional", "color": "#2a9d8f"},
]

with open("data/juegos.json", "w", encoding="utf-8") as f:
    json.dump(games, f, ensure_ascii=False, indent=2)

with open("data/discos.json", "w", encoding="utf-8") as f:
    json.dump(discos, f, ensure_ascii=False, indent=2)

print("Total juegos:", len(games))
for d in discos:
    print(d["nombre"], "->", sum(1 for g in games if g["disco"] == d["id"]))
