-- ====== Semilla de datos: discos y juegos actuales ======
-- Ejecutar DESPUES de schema.sql, una sola vez.

insert into discos (id, nombre, subtitulo, color) values
  ('1', 'Disco 1', 'Lucha y Acción Rápida', '#e63946'),
  ('3', 'Disco 3', 'Mundo Abierto, Aventura y Disparos', '#1d3557'),
  ('C', 'Colección', 'Listado Alfabético Adicional', '#2a9d8f')
on conflict (id) do nothing;

insert into juegos (id, nombre, disco, categoria, genero_original, dificultad, jugadores, resena) values
  ('d1-dragon-ball-z-budokai-tenkaichi-3', 'Dragon Ball Z: Budokai Tenkaichi 3', '1', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-mortal-kombat-armageddon', 'Mortal Kombat: Armageddon', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-mortal-kombat-deception', 'Mortal Kombat: Deception', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-tekken-5', 'Tekken 5', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-the-king-of-fighters-xi', 'The King of Fighters XI', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-the-king-of-fighters-2002-um', 'The King of Fighters 2002 UM', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-street-fighter-alpha-anthology', 'Street Fighter Alpha Anthology', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-capcom-vs-snk-2', 'Capcom vs. SNK 2', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-guilty-gear-xx-accent-core', 'Guilty Gear XX Accent Core', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-soulcalibur-iii', 'Soulcalibur III', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-def-jam-fight-for-ny', 'Def Jam: Fight for NY', '1', 'Lucha', 'Lucha / Urbano', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-naruto-ultimate-ninja-3', 'Naruto: Ultimate Ninja 3', '1', 'Lucha', 'Lucha / Anime', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-bloody-roar-4', 'Bloody Roar 4', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-virtua-fighter-4-evolution', 'Virtua Fighter 4 Evolution', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-marvel-vs-capcom-2', 'Marvel vs. Capcom 2', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-wwe-smackdown-here-comes-the-pain', 'WWE SmackDown! Here Comes the Pain', '1', 'Lucha', 'Lucha Libre', 2, '1-4', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-wwe-smackdown-vs-raw', 'WWE SmackDown! vs. RAW', '1', 'Lucha', 'Lucha Libre', 2, '1-4', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-fight-night-round-3', 'Fight Night Round 3', '1', 'Deportes', 'Deportes / Boxeo', 3, '1-2', 'Simulador deportivo para PS2 con modos de temporada, torneos y partidas rápidas.'),
  ('d1-def-jam-vendetta', 'Def Jam Vendetta', '1', 'Lucha', 'Lucha / Urbano', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-samurai-shodown-anthology', 'Samurai Shodown Anthology', '1', 'Lucha', 'Lucha / Arcade', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-metal-slug-anthology', 'Metal Slug Anthology', '1', 'Arcade', 'Arcade / Accion', 3, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('d1-bloody-roar-3', 'Bloody Roar 3', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-super-dragon-ball-z', 'Super Dragon Ball Z', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-garou-mark-of-the-wolves', 'Garou: Mark of the Wolves', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d1-svc-chaos-snk-vs-capcom', 'SVC Chaos: SNK vs. Capcom', '1', 'Lucha', 'Lucha', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('d3-grand-theft-auto-san-andreas', 'Grand Theft Auto: San Andreas', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-grand-theft-auto-vice-city', 'Grand Theft Auto: Vice City', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-grand-theft-auto-iii', 'Grand Theft Auto III', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-metal-gear-solid-3-snake-eater', 'Metal Gear Solid 3: Snake Eater', '3', 'Sigilo', 'Acción / Infiltración', 4, '1', 'Juego de sigilo y estrategia táctica. Evitá ser detectado y planificá cada movimiento.'),
  ('d3-metal-gear-solid-2-sons-of-liberty', 'Metal Gear Solid 2: Sons of Liberty', '3', 'Sigilo', 'Acción / Infiltración', 4, '1', 'Juego de sigilo y estrategia táctica. Evitá ser detectado y planificá cada movimiento.'),
  ('d3-god-of-war', 'God of War', '3', 'Hack and Slash', 'Acción / Hack and Slash', 4, '1', 'Acción frenética con combos cuerpo a cuerpo contra oleadas de enemigos.'),
  ('d3-god-of-war-ii', 'God of War II', '3', 'Hack and Slash', 'Acción / Hack and Slash', 4, '1', 'Acción frenética con combos cuerpo a cuerpo contra oleadas de enemigos.'),
  ('d3-call-of-duty-finest-hour', 'Call of Duty: Finest Hour', '3', 'Shooter', 'Shooter / Belérico', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-call-of-duty-2-big-red-one', 'Call of Duty 2: Big Red One', '3', 'Shooter', 'Shooter / Belérico', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-call-of-duty-3', 'Call of Duty 3', '3', 'Shooter', 'Shooter / Belérico', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-armored-core-last-raven', 'Armored Core: Last Raven', '3', 'Acción', 'Acción / Mecha', 4, '1', 'Título de acción para PS2 con ritmo intenso y desafíos variados.'),
  ('d3-armored-core-3', 'Armored Core 3', '3', 'Acción', 'Acción / Mecha', 4, '1', 'Título de acción para PS2 con ritmo intenso y desafíos variados.'),
  ('d3-armored-core-nexus', 'Armored Core: Nexus', '3', 'Acción', 'Acción / Mecha', 4, '1', 'Título de acción para PS2 con ritmo intenso y desafíos variados.'),
  ('d3-armored-core-nine-breaker', 'Armored Core: Nine Breaker', '3', 'Acción', 'Acción / Mecha', 4, '1', 'Título de acción para PS2 con ritmo intenso y desafíos variados.'),
  ('d3-resident-evil-4', 'Resident Evil 4', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-resident-evil-code-veronica-x', 'Resident Evil - Code: Veronica X', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-resident-evil-outbreak', 'Resident Evil Outbreak', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-resident-evil-outbreak-file-2', 'Resident Evil Outbreak: File #2', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-silent-hill-2', 'Silent Hill 2', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-silent-hill-3', 'Silent Hill 3', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-silent-hill-4-the-room', 'Silent Hill 4: The Room', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-silent-hill-origins', 'Silent Hill: Origins', '3', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('d3-medal-of-honor-frontline', 'Medal of Honor: Frontline', '3', 'Shooter', 'Shooter en Primera Persona', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-medal-of-honor-rising-sun', 'Medal of Honor: Rising Sun', '3', 'Shooter', 'Shooter / Belérico', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-medal-of-honor-european-assault', 'Medal of Honor: European Assault', '3', 'Shooter', 'Shooter / Belérico', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-shadow-of-the-colossus', 'Shadow of the Colossus', '3', 'Aventura', 'Aventura Épica', 4, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-ico', 'Ico', '3', 'Aventura', 'Aventura / Puzzle', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-okami', 'Okami', '3', 'Aventura', 'Aventura / Acción', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-devil-may-cry', 'Devil May Cry', '3', 'Hack and Slash', 'Hack and Slash', 4, '1', 'Acción frenética con combos cuerpo a cuerpo contra oleadas de enemigos.'),
  ('d3-devil-may-cry-3-dante-s-awakening', 'Devil May Cry 3: Dante''s Awakening', '3', 'Hack and Slash', 'Hack and Slash', 4, '1', 'Acción frenética con combos cuerpo a cuerpo contra oleadas de enemigos.'),
  ('d3-prince-of-persia-the-sands-of-time', 'Prince of Persia: The Sands of Time', '3', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('d3-prince-of-persia-warrior-within', 'Prince of Persia: Warrior Within', '3', 'Aventura', 'Aventura / Acción', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-prince-of-persia-the-two-thrones', 'Prince of Persia: The Two Thrones', '3', 'Aventura', 'Aventura / Acción', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-bully', 'Bully', '3', 'Mundo Abierto', 'Mundo Abierto / Acción', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-max-payne', 'Max Payne', '3', 'Shooter', 'Shooter / Noir', 4, '1', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-max-payne-2-the-fall-of-max-payne', 'Max Payne 2: The Fall of Max Payne', '3', 'Shooter', 'Shooter / Noir', 4, '1', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-need-for-speed-most-wanted', 'Need for Speed: Most Wanted', '3', 'Carreras', 'Carreras / Tuning', 3, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('d3-need-for-speed-underground-2', 'Need for Speed: Underground 2', '3', 'Carreras', 'Carreras / Tuning', 3, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('d3-burnout-3-takedown', 'Burnout 3: Takedown', '3', 'Carreras', 'Carreras / Arcade', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('d3-midnight-club-3-dub-edition', 'Midnight Club 3: DUB Edition', '3', 'Carreras', 'Carreras / Mundo Abierto', 3, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('d3-gran-turismo-4', 'Gran Turismo 4', '3', 'Carreras', 'Simulador de Conducción', 3, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('d3-gran-turismo-3-a-spec', 'Gran Turismo 3: A-Spec', '3', 'Carreras', 'Simulador de Conducción', 3, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('d3-killzone', 'Killzone', '3', 'Shooter', 'Shooter en Primera Persona', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-timesplitters-2', 'Timesplitters 2', '3', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-timesplitters-future-perfect', 'Timesplitters: Future Perfect', '3', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('d3-the-matrix-path-of-neo', 'The Matrix: Path of Neo', '3', 'Beat ''em up', 'Acción / Beat ''em up', 3, '1-2', 'Beat ''em up clásico: avanzá por el escenario repartiendo golpes contra hordas de enemigos.'),
  ('d3-enter-the-matrix', 'Enter the Matrix', '3', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-onimusha-warlords', 'Onimusha: Warlords', '3', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-onimusha-2-samurai-s-destiny', 'Onimusha 2: Samurai''s Destiny', '3', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-onimusha-3-demon-siege', 'Onimusha 3: Demon Siege', '3', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-onimusha-dawn-of-dreams', 'Onimusha: Dawn of Dreams', '3', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('d3-castlevania-curse-of-darkness', 'Castlevania: Curse of Darkness', '3', 'RPG', 'Acción / RPG', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('d3-castlevania-lament-of-innocence', 'Castlevania: Lament of Innocence', '3', 'RPG', 'Acción / RPG', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('d3-god-hand', 'God Hand', '3', 'Beat ''em up', 'Beat ''em up', 3, '1-2', 'Beat ''em up clásico: avanzá por el escenario repartiendo golpes contra hordas de enemigos.'),
  ('d3-mercenaries-playground-of-destruction', 'Mercenaries: Playground of Destruction', '3', 'Mundo Abierto', 'Acción / Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-true-crime-streets-of-la', 'True Crime: Streets of LA', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-true-crime-new-york-city', 'True Crime: New York City', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-scarface-the-world-is-yours', 'Scarface: The World is Yours', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-the-godfather', 'The Godfather', '3', 'Mundo Abierto', 'Mundo Abierto', 4, '1', 'Aventura de mundo abierto en PS2: explorá libremente, cumplí misiones y desatá el caos a tu ritmo.'),
  ('d3-hitman-blood-money', 'Hitman: Blood Money', '3', 'Sigilo', 'Sigilo / Acción', 4, '1', 'Juego de sigilo y estrategia táctica. Evitá ser detectado y planificá cada movimiento.'),
  ('d3-hitman-2-silent-assassin', 'Hitman 2: Silent Assassin', '3', 'Sigilo', 'Sigilo / Acción', 4, '1', 'Juego de sigilo y estrategia táctica. Evitá ser detectado y planificá cada movimiento.'),
  ('d3-splinter-cell-chaos-theory', 'Splinter Cell: Chaos Theory', '3', 'Sigilo', 'Sigilo / Espionaje', 4, '1', 'Juego de sigilo y estrategia táctica. Evitá ser detectado y planificá cada movimiento.'),
  ('d3-tom-clancy-s-ghost-recon', 'Tom Clancy''s Ghost Recon', '3', 'Shooter', 'Shooter Táctico', 5, '1', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-activision-anthology', 'Activision Anthology', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-alien-hominid', 'Alien Hominid', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-naruto-clash-of-ninja-revolution-3', 'Naruto: Clash of Ninja Revolution 3', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-naruto-ultimate-ninja', 'Naruto: Ultimate Ninja', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-naruto-ultimate-ninja-zero-3', 'Naruto: Ultimate Ninja Zero 3', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-art-of-fighting-anthology', 'Art of Fighting Anthology', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-atari-anthology', 'Atari Anthology', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-baldur-s-gate-dark-alliance', 'Baldur''s Gate: Dark Alliance', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-baldur-s-gate-dark-alliance-2', 'Baldur''s Gate: Dark Alliance 2', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-baroque', 'Baroque', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-battlefield-2-modern-combat', 'Battlefield 2: Modern Combat', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-blood-will-tell', 'Blood Will Tell', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-bloody-roar-3', 'Bloody Roar 3', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-burnout-3-takedown', 'Burnout 3: Takedown', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-burnout-dominator', 'Burnout Dominator', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-buzz-hollywood', 'Buzz! Hollywood', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-buzz-junior-dino-den', 'Buzz! Junior: Dino Den', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-buzz-junior-monster-rumble', 'Buzz! Junior: Monster Rumble', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-buzz-the-big-quiz', 'Buzz! The Big Quiz', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-buzz-the-pop-quiz', 'Buzz! The Pop Quiz', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-buzz-the-sports-quiz', 'Buzz! The Sports Quiz', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-buzz-qu-sabes-de-tu-pa-s', 'Buzz! ¿Qué Sabes de tu País?', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-capcom-classics-collection-vol-1', 'Capcom Classics Collection Vol.1', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-capcom-classics-collection-vol-2', 'Capcom Classics Collection Vol.2', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-castlevania-curse-of-darkness', 'Castlevania: Curse of Darkness', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-contra-shattered-soldier', 'Contra: Shattered Soldier', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-crash-bandicoot-nitro-kart', 'Crash Bandicoot: Nitro Kart', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-crash-twinsanity', 'Crash Twinsanity', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-darkwatch', 'Darkwatch', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-def-jam-fight-for-ny', 'Def Jam: Fight for NY', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-devil-may-cry-2-dante-disc', 'Devil May Cry 2 (Dante Disc)', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-devil-may-cry-2-lucia-disc', 'Devil May Cry 2 (Lucia Disc)', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-downhill-domination', 'Downhill Domination', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-dragon-blaze', 'Dragon Blaze', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-echo-night-beyond', 'Echo Night: Beyond', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-fatal-fury-battle-archives-vol-2', 'Fatal Fury Battle Archives Vol.2', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-fifa-street', 'FIFA Street', 'C', 'Deportes', 'Deportes', 2, '1-4', 'Simulador deportivo para PS2 con modos de temporada, torneos y partidas rápidas.'),
  ('dC-final-fantasy-x', 'Final Fantasy X', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-final-fantasy-x-2', 'Final Fantasy X-2', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-final-fantasy-xii', 'Final Fantasy XII', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-forgotten-realms-demon-stone', 'Forgotten Realms: Demon Stone', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-gitaroo-man', 'Gitaroo Man', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-god-of-war', 'God of War', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-god-of-war-ii', 'God of War II', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-gradius-iii-iv', 'Gradius III & IV', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-guitar-hero-iii-legends-of-rock', 'Guitar Hero III: Legends of Rock', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-gunbird-special-edition', 'Gunbird: Special Edition', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-the-guy-game', 'The Guy Game', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-the-hobbit', 'The Hobbit', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-jacked', 'Jacked', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-jak-and-daxter-the-lost-frontier', 'Jak and Daxter: The Lost Frontier', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-just-cause', 'Just Cause', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-kinetica', 'Kinetica', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-king-of-fighters-2000-2001-disc-2', 'King of Fighters 2000 & 2001 (Disc 2)', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-knights-of-the-temple-ii', 'Knights of the Temple II', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-manhunt', 'Manhunt', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-megaman-anniversary-collection', 'MegaMan Anniversary Collection', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-megaman-x-collection', 'MegaMan X Collection', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-metal-gear-solid-2-sons-of-liberty', 'Metal Gear Solid 2: Sons of Liberty', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-metal-slug-anthology', 'Metal Slug Anthology', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-midway-arcade-treasures-2', 'Midway Arcade Treasures 2', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-midway-arcade-treasures-3', 'Midway Arcade Treasures 3', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-mortal-kombat-armageddon', 'Mortal Kombat: Armageddon', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-mortal-kombat-deception', 'Mortal Kombat: Deception', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-mushihimesama', 'Mushihimesama', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-mx-vs-atv-untamed', 'MX vs. ATV Untamed', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-mx-vs-atv-unleashed', 'MX vs. ATV Unleashed', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-mx-world-tour', 'MX World Tour', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-namco-museum', 'Namco Museum', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-nba-live-09', 'NBA Live 09', 'C', 'Deportes', 'Deportes', 2, '1-4', 'Simulador deportivo para PS2 con modos de temporada, torneos y partidas rápidas.'),
  ('dC-need-for-speed-most-wanted', 'Need for Speed: Most Wanted', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-neo-contra', 'Neo Contra', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-neogeo-fatal-fury-collection', 'NeoGeo Fatal Fury Collection', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-nights-into-dreams', 'NiGHTS into Dreams...', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-ninja-assault', 'Ninja Assault', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-obscure', 'Obscure', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-obscure-ii', 'Obscure II', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-odin-sphere', 'Odin Sphere', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-onimusha-warlords', 'Onimusha: Warlords', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-onimusha-2-samurai-s-destiny', 'Onimusha 2: Samurai''s Destiny', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-onimusha-3-demon-siege', 'Onimusha 3: Demon Siege', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-outrun-2006-coast-2-coast', 'Outrun 2006: Coast 2 Coast', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-pac-man-world-rally', 'Pac-Man World Rally', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-prince-of-persia-the-sands-of-time', 'Prince of Persia: The Sands of Time', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-prince-of-persia-the-two-thrones', 'Prince of Persia: The Two Thrones', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-prince-of-persia-warrior-within', 'Prince of Persia: Warrior Within', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-primal', 'Primal', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-pro-evolution-soccer-2014', 'Pro Evolution Soccer 2014', 'C', 'Deportes', 'Deportes', 2, '1-4', 'Simulador deportivo para PS2 con modos de temporada, torneos y partidas rápidas.'),
  ('dC-project-zero', 'Project Zero', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-project-zero-2-crimson-butterfly', 'Project Zero 2: Crimson Butterfly', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-project-zero-3-the-tormented', 'Project Zero 3: The Tormented', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-the-punisher', 'The Punisher', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-radirgy-precious', 'Radirgy: Precious', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-ratchet-clank', 'Ratchet & Clank', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-ratchet-clank-2-locked-loaded', 'Ratchet & Clank 2: Locked & Loaded', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-ratchet-clank-3-up-your-arsenal', 'Ratchet & Clank 3: Up Your Arsenal', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-ratchet-deadlocked', 'Ratchet: Deadlocked', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-resident-evil-code-veronica-x', 'Resident Evil: Code Veronica X', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-resident-evil-outbreak', 'Resident Evil Outbreak', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-resident-evil-4', 'Resident Evil 4', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-resident-evil-outbreak-file-2', 'Resident Evil Outbreak: File #2', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-rule-of-rose', 'Rule of Rose', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-rumble-roses', 'Rumble Roses', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-rygar-the-legendary-adventure', 'Rygar: The Legendary Adventure', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-saint-seiya-the-sanctuary', 'Saint Seiya: The Sanctuary', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-samurai-shodown-anthology', 'Samurai Shodown Anthology', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-second-sight', 'Second Sight', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-sega-classics-collection', 'Sega Classics Collection', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-sega-genesis-collection', 'Sega Genesis Collection', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-shadow-hearts', 'Shadow Hearts', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-shadow-of-rome', 'Shadow of Rome', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-shadow-tower-abyss', 'Shadow Tower Abyss', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-shin-megami-tensei-digital-devil-saga', 'Shin Megami Tensei: Digital Devil Saga', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-silent-hill-origins', 'Silent Hill: Origins', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-silent-hill-shattered-memories', 'Silent Hill: Shattered Memories', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-silent-hill-2', 'Silent Hill 2', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-silent-hill-3', 'Silent Hill 3', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-silent-hill-4-the-room', 'Silent Hill 4: The Room', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-the-simpsons-hit-run', 'The Simpsons: Hit & Run', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-sly-3-honor-among-thieves', 'Sly 3: Honor Among Thieves', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-sly-cooper-and-the-thievius-raccoonus', 'Sly Cooper and the Thievius Raccoonus', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-sly-2-band-of-thieves', 'Sly 2: Band of Thieves', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-snk-arcade-classics-volume-1', 'SNK Arcade Classics Volume 1', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-sonic-gems-collection', 'Sonic Gems Collection', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-sonic-heroes', 'Sonic Heroes', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-sonic-riders-zero-gravity', 'Sonic Riders: Zero Gravity', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-sonic-unleashed', 'Sonic Unleashed', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-soulcalibur-iii', 'Soulcalibur III', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-soulcalibur-ii', 'Soulcalibur II', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-spartan-total-warrior', 'Spartan: Total Warrior', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-splatterhouse', 'Splatterhouse', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-spyro-a-hero-s-tail', 'Spyro: A Hero''s Tail', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-spyro-enter-the-dragonfly', 'Spyro: Enter the Dragonfly', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-street-fighter-alpha-anthology', 'Street Fighter Alpha Anthology', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-street-fighter-anniversary-collection', 'Street Fighter Anniversary Collection', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-the-suffering', 'The Suffering', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-the-suffering-ties-that-bind', 'The Suffering: Ties That Bind', 'C', 'Survival Horror', 'Survival Horror', 4, '1', 'Terror y supervivencia: recursos limitados, atmósfera opresiva y enemigos que no perdonan errores.'),
  ('dC-super-mario-64-rom', 'Super Mario 64 (ROM)', 'C', 'Plataformas', 'Aventura / Plataformas', 2, '1', 'Plataformero clásico de PS2 con saltos precisos, coleccionables y niveles llenos de estilo.'),
  ('dC-tmnt-teenage-mutant-ninja-turtles', 'TMNT: Teenage Mutant Ninja Turtles', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-taiko-no-tatsujin-10-in-1', 'Taiko no Tatsujin 10 in 1', 'C', 'Fiesta', 'Musical / Trivia', 2, '1-4', 'Juego de fiesta / trivia ideal para jugar en grupo y pasar un buen rato.'),
  ('dC-taito-legends-2', 'Taito Legends 2', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-tales-of-the-abyss', 'Tales of the Abyss', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-tekken-4', 'Tekken 4', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-tekken-5', 'Tekken 5', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-tekken-tag-tournament', 'Tekken Tag Tournament', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-the-fellowship-of-the-ring', 'The Fellowship of the Ring', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-the-hobbit-b', 'The Hobbit', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-the-king-of-fighters-10-in-1', 'The King of Fighters 10 in 1', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-the-thing', 'The Thing', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-time-crisis-2', 'Time Crisis 2', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-time-crisis-3', 'Time Crisis 3', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-timesplitters', 'TimeSplitters', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-timesplitters-future-perfect', 'TimeSplitters: Future Perfect', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-timesplitters-2', 'TimeSplitters 2', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-urban-chaos-riot-response', 'Urban Chaos: Riot Response', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-valkyrie-profile-2-silmeria', 'Valkyrie Profile 2: Silmeria', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-vampire-darkstalkers-collection', 'Vampire: Darkstalkers Collection', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-vampire-night', 'Vampire Night', 'C', 'Shooter', 'Shooter / Acción', 4, '1-2', 'Shooter de acción para PS2 con intensos tiroteos y campañas cargadas de adrenalina.'),
  ('dC-viewtiful-joe', 'Viewtiful Joe', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-viewtiful-joe-2', 'Viewtiful Joe 2', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-virtua-cop-elite-edition', 'Virtua Cop: Elite Edition', 'C', 'Lucha', 'Lucha / Acción', 3, '1-2', 'Título de combate uno contra uno para PS2. Elegí tu personaje y encadená combos para derrotar al rival.'),
  ('dC-warhammer-40-000-fire-warrior', 'Warhammer 40,000: Fire Warrior', 'C', 'RPG', 'RPG / Aventura', 3, '1', 'RPG de acción con progresión de personaje, historia profunda y combates estratégicos.'),
  ('dC-wipeout-pulse', 'Wipeout Pulse', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-world-heroes-anthology', 'World Heroes Anthology', 'C', 'Arcade', 'Arcade / Colección', 2, '1-2', 'Colección o título arcade clásico portado a PS2, ideal para partidas cortas y puntajes altos.'),
  ('dC-worms-blast', 'Worms Blast', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-xg3-extreme-g-racing', 'XG3: Extreme-G Racing', 'C', 'Carreras', 'Carreras', 2, '1-2', 'Juego de carreras para PS2 con autos personalizables y circuitos desafiantes.'),
  ('dC-yakuza', 'Yakuza', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-yakuza-2', 'Yakuza 2', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.'),
  ('dC-giga-wing-generations', 'Giga Wing Generations', 'C', 'Aventura', 'Acción / Aventura', 3, '1', 'Aventura de acción con exploración, resolución de puzzles y una historia envolvente.')
on conflict (id) do nothing;

insert into config (id, link_descarga_general) values (1, NULL) on conflict (id) do nothing;